// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdeyRYtoKPkzzK6W2ZZAliTs7IFNtBFgs',
    appId: '1:49892106354:web:134df14bb5a11020e822eb',
    messagingSenderId: '49892106354',
    projectId: 'weather-app-2a938',
    authDomain: 'weather-app-2a938.firebaseapp.com',
    storageBucket: 'weather-app-2a938.appspot.com',
    measurementId: 'G-MCN4VPSG1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNT2sSsey8MLz_YLt0KmDRAJ674RZotCo',
    appId: '1:49892106354:android:9ebb4c2c8f20a542e822eb',
    messagingSenderId: '49892106354',
    projectId: 'weather-app-2a938',
    storageBucket: 'weather-app-2a938.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtNhg9HuQs1mrAWaweO3xrfbYY1MbZ2Yg',
    appId: '1:49892106354:ios:40187e3c9743c4b3e822eb',
    messagingSenderId: '49892106354',
    projectId: 'weather-app-2a938',
    storageBucket: 'weather-app-2a938.appspot.com',
    iosBundleId: 'com.example.weatherapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtNhg9HuQs1mrAWaweO3xrfbYY1MbZ2Yg',
    appId: '1:49892106354:ios:9681b603db574c96e822eb',
    messagingSenderId: '49892106354',
    projectId: 'weather-app-2a938',
    storageBucket: 'weather-app-2a938.appspot.com',
    iosBundleId: 'com.example.weatherapp.RunnerTests',
  );
}
